//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPDCLAIMFORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPDEXPENSE_PATIENT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> AGE { get; set; }
        public int OPDEXPENSE_ID { get; set; }
        public string RELATIONSHIP_EMPLOYEE { get; set; }
    
        public virtual OPDEXPENSE OPDEXPENSE { get; set; }
    }
}
